import yfinance as yf
import schedule
import time
import pandas as pd
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import requests
from datetime import datetime
import os

# --- Load thresholds ---
with open('thresholds.json', 'r') as f:
    thresholds = json.load(f)

# --- Load config ---
with open('config.json', 'r') as f:
    config = json.load(f)

# --- CSV File for history ---
CSV_FILE = 'history.csv'
if not os.path.exists(CSV_FILE):
    df = pd.DataFrame(columns=['Timestamp', 'Stock', 'Price'])
    df.to_csv(CSV_FILE, index=False)

# --- Notification Functions ---
def send_email(subject, stock, price, threshold_type, threshold):
    email_conf = config['email']
    
    color = "green" if threshold_type == "UP" else "red"
    
    html = f"""
    <html>
    <body>
        <h2 style="color:#2E86C1;">Bursa Stock Alert</h2>
        <p>Stock: <b>{stock}</b></p>
        <p>Current Price: <b>{price}</b></p>
        <p style="color:{color};">Alert Type: <b>{threshold_type}</b> | Threshold: {threshold}</p>
        <hr>
        <p>Generated by <b>Bursa Stock Tracker</b> at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['From'] = email_conf['email_address']
    msg['To'] = email_conf['email_address']
    msg['Subject'] = subject
    msg.attach(MIMEText(html, 'html'))

    try:
        server = smtplib.SMTP(email_conf['smtp_server'], email_conf['smtp_port'])
        server.starttls()
        server.login(email_conf['email_address'], email_conf['password'])
        server.send_message(msg)
        server.quit()
        print(f"[Email] Alert sent: {subject}")
    except Exception as e:
        print(f"[Email] Failed to send alert: {e}")

def send_telegram(message):
    telegram_conf = config['telegram']
    url = f"https://api.telegram.org/bot{telegram_conf['bot_token']}/sendMessage"
    payload = {
        'chat_id': telegram_conf['chat_id'],
        'text': message
    }
    try:
        requests.post(url, data=payload)
        print(f"[Telegram] Alert sent: {message}")
    except Exception as e:
        print(f"[Telegram] Failed to send alert: {e}")

# --- Monitoring Function ---
def check_stocks():
    for stock, limits in thresholds.items():
        ticker = yf.Ticker(stock)
        try:
            price = ticker.history(period="1d")['Close'].iloc[-1]
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            print(f"{timestamp} | {stock} price: {price}")

            # Save to CSV
            df = pd.DataFrame([[timestamp, stock, price]], columns=['Timestamp', 'Stock', 'Price'])
            df.to_csv(CSV_FILE, mode='a', header=False, index=False)

            # Check thresholds
            if price >= limits['up']:
                send_email(
                    subject=f"{stock} Price UP Alert!",
                    stock=stock,
                    price=price,
                    threshold_type="UP",
                    threshold=limits['up']
                )
                send_telegram(f"{stock} price UP alert! Current: {price}, Threshold: {limits['up']}")
            elif price <= limits['down']:
                send_email(
                    subject=f"{stock} Price DOWN Alert!",
                    stock=stock,
                    price=price,
                    threshold_type="DOWN",
                    threshold=limits['down']
                )
                send_telegram(f"{stock} price DOWN alert! Current: {price}, Threshold: {limits['down']}")

        except Exception as e:
            print(f"Failed to fetch {stock} price: {e}")

# --- Scheduler ---
schedule.every(5).minutes.do(check_stocks)  # Check every 5 minutes

print("Bursa Stock Tracker started...")
check_stocks()  # Initial check

while True:
    schedule.run_pending()
    time.sleep(1)
